# Instalando Bibliotecas Adicionais

In [ ]:
!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip &> /dev/null

# Importando Bibliotecas

In [ ]:
import altair as alt
import pandas as pd
from ipywidgets import interact
from pandas_profiling import ProfileReport
from tabulate import tabulate

# Carregando os Dados

In [ ]:
df_desmat = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dados_desmatamento.csv')

df_desmat

          Lat      Long  ... PercDesmatado2018 PercDesmatado2019
0    -3.25303 -45.97435  ...          0.828753          0.829204
1    -6.84864 -49.25551  ...          0.891062          0.891405
2   -10.61178 -68.46285  ...          0.260533          0.271838
3    -6.59866 -48.48198  ...          0.839127          0.839547
4    -6.88444 -47.99094  ...          0.230174          0.230608
..        ...       ...  ...               ...               ...
755  -2.03379 -48.31904  ...          0.551020          0.555217
756  -4.70208 -47.22036  ...          0.913308          0.915087
757  -9.46606 -49.33901  ...          0.005211          0.005211
758  -4.96265 -48.39406  ...          0.921591          0.928409
759  -1.73866 -48.85524  ...          0.430921          0.431169

[760 rows x 41 columns]

In [ ]:
df_desmat_ano = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dados_desmatamento_col_ano.csv')

df_desmat_ano

           Lat      Long        Municipio  ... Desmatado  Incremento  PercDesmatado
0     -3.25303 -45.97435          Zé Doca  ...    1953.9         3.6       0.801436
1     -6.84864 -49.25551         Xinguara  ...    3363.2         4.8       0.886686
2    -10.61178 -68.46285           Xapuri  ...    1257.3        23.8       0.228144
3     -6.59866 -48.48198          Xambioá  ...     977.5         7.8       0.820739
4     -6.88444 -47.99094     Wanderlândia  ...     314.6         2.4       0.227641
...        ...       ...              ...  ...       ...         ...            ...
9115  -2.03379 -48.31904            Acará  ...    2421.3        18.3       0.555217
9116  -4.70208 -47.22036       Açailândia  ...    5349.6        10.3       0.915087
9117  -9.46606 -49.33901      Abreulândia  ...       9.9         0.0       0.005211
9118  -4.96265 -48.39406  Abel Figueiredo  ...     571.9         4.2       0.928409
9119  -1.73866 -48.85524       Abaetetuba  ...     697.2         0.3       0.431169

[9120 rows x 9 columns]

In [ ]:
df_desmat_estados = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dados_desmatamento_estado.csv')

df_desmat_estados

  Estado  AreaKm2  ...  PercDesmatado2018  PercDesmatado2019
0     AC   170884  ...           0.136319           0.140640
1     AM  1589661  ...           0.025354           0.026355
2     AP   142918  ...           0.021506           0.021780
3     MA   264626  ...           0.401422           0.402493
4     MT   904794  ...           0.239653           0.241758
5     PA  1249644  ...           0.213975           0.217553
6     RO   240374  ...           0.388296           0.394249
7     RR   226216  ...           0.047549           0.050001
8     TO   278931  ...           0.109822           0.109933

[9 rows x 38 columns]

In [ ]:
df_desmat_estados_ano = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dados_desmatamento_estado_col_ano.csv')

df_desmat_estados_ano

    Estado  AreaKm2   Ano  Desmatado  Incremento  PercDesmatado
0       AC   170884  2008    20340.4       299.2       0.119030
1       AM  1589661  2008    33502.7       622.6       0.021075
2       AP   142918  2008     2792.3        99.0       0.019538
3       MA   264626  2008   102550.1      1258.2       0.387528
4       MT   904794  2008   205177.3      3449.5       0.226767
..     ...      ...   ...        ...         ...            ...
103     MT   904794  2019   218741.4      1905.1       0.241758
104     PA  1249644  2019   271863.3      4469.7       0.217553
105     RO   240374  2019    94767.2      1430.9       0.394249
106     RR   226216  2019    11311.1       554.8       0.050001
107     TO   278931  2019    30663.7        31.1       0.109933

[108 rows x 6 columns]

In [ ]:
df_hosp = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dengue_internacoes.csv')

df_hosp

        Municipio  CodIbge Estado  2008  2009  ...  2015  2016  2017  2018  2019
0      Acrelândia   120001     AC   0.0   7.0  ...   0.0   0.0   4.0   3.0   1.0
1    Assis Brasil   120005     AC   2.0   2.0  ...   1.0   3.0   0.0   0.0   2.0
2       Brasiléia   120010     AC   1.0  63.0  ...  14.0  19.0   7.0   9.0  16.0
3          Bujari   120013     AC   1.0   1.0  ...   0.0   0.0   0.0   0.0   0.0
4        Capixaba   120017     AC   3.0   5.0  ...   1.0   4.0   0.0   3.0   3.0
..            ...      ...    ...   ...   ...  ...   ...   ...   ...   ...   ...
785    Tocantínia   172110     TO   4.0   0.0  ...   2.0   0.0   1.0   1.0   8.0
786      Tupirama   172125     TO   3.0   6.0  ...   1.0   0.0   1.0   0.0   1.0
787    Tupiratins   172130     TO   4.0   2.0  ...   0.0   0.0   0.0   0.0   2.0
788  Wanderlândia   172208     TO   5.0   3.0  ...   0.0   0.0   0.0   1.0   2.0
789       Xambioá   172210     TO  40.0  37.0  ...   1.0  12.0  19.0   5.0  24.0

[790 rows x 15 columns]

In [ ]:
df_hosp_ano = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dengue_internacoes_col_ano.csv')

df_hosp_ano

         Municipio  CodIbge Estado   Ano  Internações - Dengue
0       Acrelândia   120001     AC  2008                   0.0
1     Assis Brasil   120005     AC  2008                   2.0
2        Brasiléia   120010     AC  2008                   1.0
3           Bujari   120013     AC  2008                   1.0
4         Capixaba   120017     AC  2008                   3.0
...            ...      ...    ...   ...                   ...
9475    Tocantínia   172110     TO  2019                   8.0
9476      Tupirama   172125     TO  2019                   1.0
9477    Tupiratins   172130     TO  2019                   2.0
9478  Wanderlândia   172208     TO  2019                   2.0
9479       Xambioá   172210     TO  2019                  24.0

[9480 rows x 5 columns]

In [ ]:
df_hosp_estados = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dengue_internacoes_estado.csv')

df_hosp_estados

  Estado    2008    2009    2010    2011  ...    2015    2016    2017   2018    2019
0     AC   150.0   652.0   754.0   455.0  ...   351.0   109.0    79.0  207.0   277.0
1     AM   881.0   220.0   701.0  1853.0  ...   319.0   261.0   112.0   59.0   142.0
2     AP   166.0   133.0   205.0   229.0  ...   191.0     0.0     0.0   36.0     0.0
3     MA  3000.0  2254.0  3645.0  5835.0  ...  3963.0  5124.0  2205.0  549.0  1963.0
4     MT   745.0  4619.0  3804.0   988.0  ...   902.0   681.0   363.0  387.0   735.0
5     PA  7797.0  4742.0  7412.0  7848.0  ...  2326.0  3045.0  2170.0  831.0  1082.0
6     RO  1076.0  4130.0  4423.0  2078.0  ...  1252.0  1469.0   587.0  338.0   429.0
7     RR   951.0   754.0  1188.0   234.0  ...   122.0    41.0     0.0    0.0   123.0
8     TO  1195.0   946.0  1224.0  1038.0  ...   483.0   393.0   299.0  164.0   569.0

[9 rows x 13 columns]

In [ ]:
df_hosp_estados_ano = pd.read_csv(
    f'https://raw.githubusercontent.com/george-gca/MO826_IA368_CF044/main/data/processed/dengue_internacoes_estado_col_ano.csv')

df_hosp_estados_ano

    Estado   Ano  Internações - Dengue
0       AC  2008                 150.0
1       AM  2008                 881.0
2       AP  2008                 166.0
3       MA  2008                3000.0
4       MT  2008                 745.0
..     ...   ...                   ...
103     MT  2019                 735.0
104     PA  2019                1082.0
105     RO  2019                 429.0
106     RR  2019                 123.0
107     TO  2019                 569.0

[108 rows x 3 columns]

# Pareando os Dados

Verificando a quantidade de municípios em cada dado

In [ ]:
print(f'Municípios com dados de desmatamento: {len(df_desmat):n}')
print(f'Municípios com dados de internação: {len(df_hosp):n}')

Municípios com dados de desmatamento: 760
Municípios com dados de internação: 790

Verificando a quantidade de municípios com nome único em cada dado

In [ ]:
desmat_cities = df_desmat.Municipio.unique()
hosp_cities = df_hosp.Municipio.unique()
print(f'Municípios com dados de desmatamento: {len(desmat_cities):n}')
print(f'Municípios com dados de internação: {len(hosp_cities):n}')

Municípios com dados de desmatamento: 755
Municípios com dados de internação: 790

Municipios repetidos em desmatamento

In [ ]:
df_desmat[df_desmat.Municipio.duplicated()]

          Lat      Long  ... PercDesmatado2018 PercDesmatado2019
191 -15.28141 -58.15176  ...          0.843289          0.843478
209  -2.30799 -45.76410  ...          0.998413          0.998413
268  -7.55219 -48.99658  ...          0.820420          0.820492
645  -9.00182 -47.86311  ...          0.005605          0.005605
702  -3.06101 -45.77225  ...          0.934402          0.934402

[5 rows x 41 columns]

In [ ]:
for city in df_desmat[df_desmat.Municipio.duplicated()].Municipio:
  print(f'{df_desmat[df_desmat.Municipio == city][df_desmat.columns[:4]]}\n')

          Lat      Long   Municipio Estado
190  -9.99527 -68.15925  Rio Branco     AC
191 -15.28141 -58.15176  Rio Branco     MT

          Lat      Long          Municipio Estado
208 -11.19374 -61.84743  Presidente Médici     RO
209  -2.30799 -45.76410  Presidente Médici     MA

         Lat      Long   Municipio Estado
267 -7.72486 -50.13413  Pau D'Arco     PA
268 -7.55219 -48.99658  Pau D'Arco     TO

         Lat      Long               Municipio Estado
644 -5.02798 -48.77112  Bom Jesus do Tocantins     PA
645 -9.00182 -47.86311  Bom Jesus do Tocantins     TO

         Lat      Long Municipio Estado
701 -6.73568 -48.55630  Araguanã     TO
702 -3.06101 -45.77225  Araguanã     MA

Municípios que só aparecem em dados hospitalares

In [ ]:
cities_only_in_hosp = {c for c in hosp_cities if c not in desmat_cities}
df_only_in_hosp = df_hosp[df_hosp.Municipio.isin(cities_only_in_hosp)]
df_only_in_hosp

                      Municipio  CodIbge Estado  ...   2017  2018  2019
91                 Afonso Cunha   210010     MA  ...    0.0   1.0   4.0
92        Água Doce do Maranhão   210015     MA  ...    1.0   1.0   0.0
94                Aldeias Altas   210030     MA  ...  208.0  77.0  24.0
102                    Anapurus   210080     MA  ...    3.0  10.0  31.0
105                    Araioses   210090     MA  ...   14.0   1.0   7.0
113             Barão de Grajaú   210150     MA  ...   21.0   9.0  34.0
115                Barreirinhas   210170     MA  ...    1.0   0.0   1.0
117                     Belágua   210173     MA  ...    1.0   0.0   0.0
125                       Brejo   210210     MA  ...    8.0   1.0   1.0
127                      Buriti   210220     MA  ...    2.0   0.0   2.0
128                Buriti Bravo   210230     MA  ...    2.0   3.0   9.0
131            Cachoeira Grande   210237     MA  ...    1.0   0.0   0.0
140                      Caxias   210300     MA  ...    4.0   0.0  10.0
145                  Chapadinha   210320     MA  ...    1.0   0.0   7.0
147                        Codó   210330     MA  ...    2.0   2.0   4.0
148                 Coelho Neto   210340     MA  ...    0.0   1.0   1.0
155               Duque Bacelar   210390     MA  ...    1.0   2.0   1.0
174          Humberto de Campos   210500     MA  ...    0.0   0.0   0.0
175                       Icatu   210510     MA  ...    0.0   0.0   0.0
191               Lagoa do Mato   210592     MA  ...    1.0   1.0   1.0
197        Magalhães de Almeida   210630     MA  ...    0.0   1.0   1.0
201                   Mata Roma   210640     MA  ...    2.0   0.0  26.0
203                      Matões   210660     MA  ...    8.0   2.0   4.0
205        Milagres do Maranhão   210667     MA  ...    1.0   0.0   0.0
211                      Morros   210710     MA  ...    0.0   0.0   0.0
212              Nina Rodrigues   210720     MA  ...    0.0   0.0   0.0
220                   Paraibano   210770     MA  ...   47.0   0.0  28.0
221                   Parnarama   210780     MA  ...    1.0   1.0   2.0
222             Passagem Franca   210790     MA  ...   31.0   3.0   8.0
224               Paulino Neves   210805     MA  ...    6.0   3.0   7.0
242           Presidente Vargas   210930     MA  ...   11.0  11.0   0.0
243               Primeira Cruz   210940     MA  ...    5.0   0.0   0.0
254  Santa Quitéria do Maranhão   211010     MA  ...    0.0   0.0   0.0
256         Santana do Maranhão   211023     MA  ...    1.0   0.0   0.0
257     Santo Amaro do Maranhão   211027     MA  ...    0.0   0.0   0.0
259   São Benedito do Rio Preto   211040     MA  ...    2.0   1.0   0.0
261                São Bernardo   211060     MA  ...    6.0   1.0   3.0
266   São Francisco do Maranhão   211090     MA  ...    5.0   9.0  45.0
270           São João do Soter   211107     MA  ...   33.0   4.0   4.0
271          São João dos Patos   211110     MA  ...   30.0   4.0  17.0
284     Senador Alexandre Costa   211174     MA  ...    3.0   1.0   2.0
289         Sucupira do Riachão   211195     MA  ...    4.0   1.0  14.0
291                    Timbiras   211210     MA  ...    7.0   0.0   2.0
292                       Timon   211220     MA  ...  130.0   3.0  10.0
298                      Tutóia   211250     MA  ...    8.0   2.0   6.0
299               Urbano Santos   211260     MA  ...    6.0   0.0   1.0
300               Vargem Grande   211270     MA  ...    8.0   1.0   4.0
491         Eldorado do Carajás   150295     PA  ...    0.0   0.0   1.0
551        Santa Izabel do Pará   150650     PA  ...    0.0   4.0   1.0
779                 São Valério   172049     TO  ...    0.0   0.0   0.0

[50 rows x 15 columns]

Municípios que só aparecem em dados de desmatamento

In [ ]:
cities_only_in_desmat = {c for c in desmat_cities if c not in hosp_cities}
df_only_in_desmat = df_desmat[df_desmat.Municipio.isin(cities_only_in_desmat)]
df_only_in_desmat

          Lat      Long  ... PercDesmatado2018 PercDesmatado2019
23   -1.24938 -58.78714  ...          0.012352          0.012395
28   -3.20648 -65.43058  ...          0.025842          0.026091
41   -2.57583 -67.47268  ...          0.014171          0.014202
65  -12.08831 -48.85414  ...          0.000000          0.000000
85  -11.77169 -48.22797  ...          0.000000          0.000000
86   -1.89625 -58.81001  ...          0.020601          0.020852
160  -1.36752 -48.12871  ...          0.746944          0.746944
216   1.61009 -50.73654  ...          0.016878          0.017200
339  -1.08094 -58.44390  ...          0.035352          0.035558
385  -3.73889 -60.65552  ...          0.125194          0.125594
516  -6.12012 -49.26085  ...          0.928167          0.929346
529   1.06660 -50.32807  ...          0.088427          0.088805
653  -4.54242 -61.73805  ...          0.012998          0.013158
677  -2.69129 -44.65781  ...          0.023684          0.023684
713  -4.15477 -62.08065  ...          0.014269          0.014269

[15 rows x 41 columns]

# Unificando os Dados em um Único DataFrame

Removendo municípios que só existem nos dados hospitalares

In [ ]:
df_hosp_clean = df_hosp.drop(df_only_in_hosp.index)
print(f'Dados de internação antes: {len(df_hosp):n}')
print(f'Dados de internação depois: {len(df_hosp_clean):n}')

Dados de internação antes: 790
Dados de internação depois: 740

Removendo municípios que só existem nos dados de desmatamento

In [ ]:
df_desmat_clean = df_desmat.drop(df_only_in_desmat.index)
print(f'Dados de desmatamento antes: {len(df_desmat):n}')
print(f'Dados de desmatamento depois: {len(df_desmat_clean):n}')

Dados de desmatamento antes: 760
Dados de desmatamento depois: 745

Ainda há 5 municípios a mais em desmatamento. Provavelmente são os municípios de mesmo nome. Vamos confirmar.

In [ ]:
for city in df_desmat_clean[df_desmat_clean.Municipio.duplicated()].Municipio:
  print(f'{df_desmat_clean[df_desmat_clean.Municipio == city][df_desmat_clean.columns[:4]]}\n')

          Lat      Long   Municipio Estado
190  -9.99527 -68.15925  Rio Branco     AC
191 -15.28141 -58.15176  Rio Branco     MT

          Lat      Long          Municipio Estado
208 -11.19374 -61.84743  Presidente Médici     RO
209  -2.30799 -45.76410  Presidente Médici     MA

         Lat      Long   Municipio Estado
267 -7.72486 -50.13413  Pau D'Arco     PA
268 -7.55219 -48.99658  Pau D'Arco     TO

         Lat      Long               Municipio Estado
644 -5.02798 -48.77112  Bom Jesus do Tocantins     PA
645 -9.00182 -47.86311  Bom Jesus do Tocantins     TO

         Lat      Long Municipio Estado
701 -6.73568 -48.55630  Araguanã     TO
702 -3.06101 -45.77225  Araguanã     MA

De fato, são os municípios de mesmo nome. Removendo os municípios de mesmo nome que não existem nos dados hospitalares e juntando ambos em um único DataFrame.

In [ ]:
df_all = df_desmat_clean.merge(df_hosp_clean, on=['Municipio', 'Estado'])
df_all.sort_values(by=['Municipio'], ignore_index=True, inplace=True)
df_all.rename(columns={f'{year}': f'Internacoes{year}' for year in range(2008, 2020)}, inplace=True)
df_all

          Lat      Long  ... Internacoes2018 Internacoes2019
0    -1.73866 -48.85524  ...             9.0             7.0
1    -4.96265 -48.39406  ...             1.0             7.0
2    -9.46606 -49.33901  ...             0.0             0.0
3    -2.03379 -48.31904  ...             2.0             2.0
4   -15.19422 -56.31716  ...             0.0             0.0
..        ...       ...  ...             ...             ...
735  -6.84864 -49.25551  ...             5.0            17.0
736  -3.25303 -45.97435  ...             4.0             8.0
737  -6.76170 -50.32800  ...             1.0            35.0
738 -14.08771 -52.43685  ...             1.0            10.0
739   0.07317 -55.75937  ...             1.0             1.0

[740 rows x 54 columns]

Gerando agora a visualização com anos em uma coluna específica

In [ ]:
column_types = ['Desmatado', 'Incremento'] #, 'Floresta', 'Nuvem', 'NaoObservado', 'NaoFloresta', 'Hidrografia', 'PercDesmatado'] #, 'PercIncremento']

In [ ]:
dfs_alts = []

# doing melt for the first year
column_type = column_types[0]
columns_of_interest = list(df_all.columns[:5]) + [c for c in df_all.columns if c.startswith(column_type)]
print(f'Colunas de interesse: {columns_of_interest}')
df_tmp = df_all[columns_of_interest]
df_tmp = df_tmp.rename(columns={c: c[-4:] for c in columns_of_interest[5:]})
df_tmp = df_tmp.melt(id_vars=columns_of_interest[:5],
        var_name='Ano',
        value_name=column_type)
dfs_alts.append(df_tmp)

# doing melt for the rest of the years
for column_type in column_types[1:]:
  columns_of_interest = ['Municipio'] + [c for c in df_all.columns if c.startswith(column_type)]
  print(f'Colunas de interesse: {columns_of_interest}')
  df_tmp = df_all[columns_of_interest]
  df_tmp = df_tmp.rename(columns={c: c[-4:] for c in columns_of_interest[1:]})
  df_tmp = df_tmp.melt(id_vars=columns_of_interest[:1], 
          var_name='Ano', 
          value_name=column_type)
  
  dfs_alts.append(df_tmp[df_tmp.columns[2:]])

columns_of_interest = ['Municipio'] + [f'Internacoes{year}' for year in range(2008, 2020)]
print(f'Colunas de interesse: {columns_of_interest}')
df_tmp = df_all[columns_of_interest]
df_tmp = df_tmp.melt(id_vars=columns_of_interest[:1], 
        var_name='Ano', 
        value_name='Internações - Dengue')

dfs_alts.append(df_tmp[df_tmp.columns[2:]])

df_all_alt = pd.concat(dfs_alts, axis=1)

Colunas de interesse: ['Lat', 'Long', 'Municipio', 'Estado', 'AreaKm2', 'Desmatado2008', 'Desmatado2009', 'Desmatado2010', 'Desmatado2011', 'Desmatado2012', 'Desmatado2013', 'Desmatado2014', 'Desmatado2015', 'Desmatado2016', 'Desmatado2017', 'Desmatado2018', 'Desmatado2019']
Colunas de interesse: ['Municipio', 'Incremento20072008', 'Incremento20082009', 'Incremento20092010', 'Incremento20102011', 'Incremento20112012', 'Incremento20122013', 'Incremento20132014', 'Incremento20142015', 'Incremento20152016', 'Incremento20162017', 'Incremento20172018', 'Incremento20182019']
Colunas de interesse: ['Municipio', 'Internacoes2008', 'Internacoes2009', 'Internacoes2010', 'Internacoes2011', 'Internacoes2012', 'Internacoes2013', 'Internacoes2014', 'Internacoes2015', 'Internacoes2016', 'Internacoes2017', 'Internacoes2018', 'Internacoes2019']

In [ ]:
df_all_alt

           Lat      Long  ... Incremento Internações - Dengue
0     -1.73866 -48.85524  ...        1.2                 88.0
1     -4.96265 -48.39406  ...        2.0                 12.0
2     -9.46606 -49.33901  ...        1.9                  0.0
3     -2.03379 -48.31904  ...       47.9                 86.0
4    -15.19422 -56.31716  ...        0.0                  0.0
...        ...       ...  ...        ...                  ...
8875  -6.84864 -49.25551  ...        1.2                 17.0
8876  -3.25303 -45.97435  ...        1.1                  8.0
8877  -6.76170 -50.32800  ...        9.7                 35.0
8878 -14.08771 -52.43685  ...        0.0                 10.0
8879   0.07317 -55.75937  ...       35.0                  1.0

[8880 rows x 9 columns]

Aglutinando as informações por estado

In [ ]:
df_states = df_all.groupby(['Estado']).sum().reset_index()
columns = list(df_states.columns)
columns = [columns[0]] + columns[3:]
print(f'Deixando somente as colunas:\n{columns}')
df_states = df_states[columns]

Deixando somente as colunas:
['Estado', 'AreaKm2', 'Desmatado2008', 'Incremento20072008', 'Desmatado2009', 'Incremento20082009', 'Desmatado2010', 'Incremento20092010', 'Desmatado2011', 'Incremento20102011', 'Desmatado2012', 'Incremento20112012', 'Desmatado2013', 'Incremento20122013', 'Desmatado2014', 'Incremento20132014', 'Desmatado2015', 'Incremento20142015', 'Desmatado2016', 'Incremento20152016', 'Desmatado2017', 'Incremento20162017', 'Desmatado2018', 'Incremento20172018', 'Desmatado2019', 'Incremento20182019', 'PercDesmatado2008', 'PercDesmatado2009', 'PercDesmatado2010', 'PercDesmatado2011', 'PercDesmatado2012', 'PercDesmatado2013', 'PercDesmatado2014', 'PercDesmatado2015', 'PercDesmatado2016', 'PercDesmatado2017', 'PercDesmatado2018', 'PercDesmatado2019', 'CodIbge', 'Internacoes2008', 'Internacoes2009', 'Internacoes2010', 'Internacoes2011', 'Internacoes2012', 'Internacoes2013', 'Internacoes2014', 'Internacoes2015', 'Internacoes2016', 'Internacoes2017', 'Internacoes2018', 'Internacoes2019']

In [ ]:
df_states

  Estado  AreaKm2  ...  Internacoes2018  Internacoes2019
0     AC   170884  ...            207.0            277.0
1     AM  1492410  ...             59.0            142.0
2     AP   135836  ...             36.0              0.0
3     MA   263942  ...            392.0           1642.0
4     MT   904265  ...            387.0            735.0
5     PA  1245956  ...            827.0           1080.0
6     RO   238601  ...            338.0            429.0
7     RR   226216  ...              0.0            123.0
8     TO   271812  ...            164.0            569.0

[9 rows x 51 columns]

Gerando agora a visualização com anos em uma coluna específica

In [ ]:
dfs_alts = []

column_type = column_types[0]
columns_of_interest = list(df_states.columns[:2]) + [c for c in df_states.columns if c.startswith(column_type)]
print(f'Colunas de interesse: {columns_of_interest}')
df_tmp = df_states[columns_of_interest]
df_tmp = df_tmp.rename(columns={c: c[-4:] for c in columns_of_interest[2:]})
df_tmp = df_tmp.melt(id_vars=columns_of_interest[:2],
        var_name='Ano',
        value_name=column_type)
dfs_alts.append(df_tmp)

for column_type in column_types[1:]:
  columns_of_interest = ['Estado'] + [c for c in df_states.columns if c.startswith(column_type)]
  print(f'Colunas de interesse: {columns_of_interest}')
  df_tmp = df_states[columns_of_interest]
  df_tmp = df_tmp.rename(columns={c: c[-4:] for c in columns_of_interest[1:]})
  df_tmp = df_tmp.melt(id_vars=columns_of_interest[:1], 
          var_name='Ano', 
          value_name=column_type)
  
  dfs_alts.append(df_tmp[df_tmp.columns[2:]])

columns_of_interest = ['Estado'] + [f'Internacoes{year}' for year in range(2008, 2020)]
print(f'Colunas de interesse: {columns_of_interest}')
df_tmp = df_states[columns_of_interest]
df_tmp = df_tmp.melt(id_vars=columns_of_interest[:1], 
        var_name='Ano', 
        value_name='Internações - Dengue')

dfs_alts.append(df_tmp[df_tmp.columns[2:]])

df_states_alt = pd.concat(dfs_alts, axis=1)

Colunas de interesse: ['Estado', 'AreaKm2', 'Desmatado2008', 'Desmatado2009', 'Desmatado2010', 'Desmatado2011', 'Desmatado2012', 'Desmatado2013', 'Desmatado2014', 'Desmatado2015', 'Desmatado2016', 'Desmatado2017', 'Desmatado2018', 'Desmatado2019']
Colunas de interesse: ['Estado', 'Incremento20072008', 'Incremento20082009', 'Incremento20092010', 'Incremento20102011', 'Incremento20112012', 'Incremento20122013', 'Incremento20132014', 'Incremento20142015', 'Incremento20152016', 'Incremento20162017', 'Incremento20172018', 'Incremento20182019']
Colunas de interesse: ['Estado', 'Internacoes2008', 'Internacoes2009', 'Internacoes2010', 'Internacoes2011', 'Internacoes2012', 'Internacoes2013', 'Internacoes2014', 'Internacoes2015', 'Internacoes2016', 'Internacoes2017', 'Internacoes2018', 'Internacoes2019']

In [ ]:
df_states_alt

    Estado  AreaKm2   Ano  Desmatado  Incremento  Internações - Dengue
0       AC   170884  2008    20340.4       299.2                 150.0
1       AM  1492410  2008    31428.1       603.1                 881.0
2       AP   135836  2008     2543.0        91.9                 166.0
3       MA   263942  2008   102533.9      1258.2                2094.0
4       MT   904265  2008   204731.4      3449.5                 745.0
..     ...      ...   ...        ...         ...                   ...
103     MT   904265  2019   218295.2      1905.0                 735.0
104     PA  1245956  2019   268567.2      4466.2                1080.0
105     RO   238601  2019    93156.9      1429.8                 429.0
106     RR   226216  2019    11311.1       554.8                 123.0
107     TO   271812  2019    28778.9        30.9                 569.0

[108 rows x 6 columns]

# Salvando Dados Conjuntos

In [ ]:
df_all.to_csv('dados_conjuntos.csv', index=False)
df_all_alt.to_csv('dados_conjuntos_col_ano.csv', index=False)
df_states.to_csv('dados_conjuntos_estado.csv', index=False)
df_states_alt.to_csv('dados_conjuntos_estado_col_ano.csv', index=False)